clone:
  default:
    image: plugins/git
    recursive: true
    group: clone
    submodule_update_remote: true
    submodule_override:
       docs-theme: https://github.com/PressLabs/docs-theme.git

  presslabs-org:
    image: alpine/git
    group: clone
    commands:
      # write the ssh key to disk
      - mkdir /root/.ssh
      - echo -n "$GIT_PUSH_SSH_KEY" > /root/.ssh/id_rsa
      - chmod 600 /root/.ssh/id_rsa

      # add github to known hosts
      - touch /root/.ssh/known_hosts
      - chmod 600 /root/.ssh/known_hosts
      - ssh-keyscan -H github.com > /etc/ssh/ssh_known_hosts 2> /dev/null

      # clone presslabs-org
      - git clone -b prod git@github.com:/PressLabs/presslabs-org.git /drone/src/presslabs-org
    secrets:
      - GIT_PUSH_SSH_KEY

pipeline:
  build-docs:
    image: jobandtalent/mkdocs
    group: build
    commands:
      - cd docs/
      - mkdocs build --clean
      - for i in $(ls | grep -v compiled_docs); do rm -rf $i; done
      - mkdir -p /drone/src/presslabs-org/wp-content/root/toplytics/docs
      - rm -rf /drone/src/presslabs-org/wp-content/root/toplytics/docs/*
      - mv compiled_docs/* /drone/src/presslabs-org/wp-content/root/toplytics/docs
      - rm -rf compiled_docs/
    when:
      branch: master

  update-presslabs-org:
    image: appleboy/drone-git-push
    branch: prod
    group: docs
    commit: true
    path: /drone/src/presslabs-org
    commit_message: "[docs] Update toplytics docs"
    remote: git@github.com:/Presslabs/presslabs-org.git
    secrets:
      - GIT_PUSH_SSH_KEY
    when:
      branch: master

workspace:
   base: /drone
   path: src/toplytics
