kind: pipeline
name: default

clone:
  disable: true

workspace:
  base: /workspace
  path: src/github.com/presslabs/build

steps:
- name: clone
  image: plugins/git
  settings:
    depth: 0
    tags: true

- name: install dependencies
  image: quay.io/presslabs/build:latest
  commands:
  - make -j4 build.tools

- name: build
  pull: true
  image: quay.io/presslabs/build:latest
  environment:
    DOCKER_HOST: "unix:///workspace/docker.sock"
  commands:
  - make -j4 build

- name: publish
  image: quay.io/presslabs/build:latest
  commands:
  - /usr/local/bin/setup-credentials-helper.sh
  - make publish
  environment:
    DOCKER_HOST: "unix:///workspace/docker.sock"
    DOCKER_USERNAME: presslabsbot
    DOCKER_PASSWORD:
      from_secret: DOCKER_PASSWORD
  when:
    ref:
    - refs/heads/master-*
    - refs/heads/release-*

services:
- name: docker
  image: docker:dind
  privileged: true
  commands:
    - /usr/local/bin/dockerd-entrypoint.sh dockerd --host "unix:///workspace/docker.sock" --storage-driver overlay2 --log-level error


trigger:
  ref:
    - refs/pull/**
    - refs/heads/**
