kind: pipeline
name: default

clone:
  disable: true

workspace:
  base: /workspace
  path: src/github.com/presslabs/build

steps:
- name: clone
  image: plugins/git
  settings:
    depth: 0
    tags: true

- name: install dependencies
  image: docker.io/bitpoke/build:v0.6.0
  commands:
  - make -j4 build.tools

- name: build
  pull: true
  image: quay.io/presslabs/build:latest
  commands:
  - dockerize -wait http://docker:2375/_ping -timeout 30s
  - make -j4 build
  depends_on:
    - clone

- name: publish
  image: quay.io/presslabs/build:latest
  commands:
  - /usr/local/bin/setup-credentials-helper.sh
  - make publish
  environment:
    DOCKER_USERNAME: presslabsbot
    DOCKER_PASSWORD:
      from_secret: DOCKER_PASSWORD
  depends_on:
    - build

services:
- name: docker
  image: docker:20.10.8-dind-rootless
  environment:
    DOCKER_TLS_CERTDIR: ""

trigger:
  ref:
    - refs/heads/master
    - refs/heads/master-*
    - refs/pull/**
    - refs/heads/**
