---
clone:
  disable: true
kind: pipeline
name: php-8.0
services:
- environment:
    MYSQL_DATABASE: wordpress_test
    MYSQL_PASSWORD: wordpress
    MYSQL_ROOT_PASSWORD: test
    MYSQL_USER: wordpress
  image: percona:5.7
  name: database
  pull: always
steps:
- image: plugins/git
  name: git
  pull: default
  settings:
    depth: 0
    tags: true
- commands:
  - make test WP_VERSION=6.0.1
  environment:
    WORDPRESS_TEST_DB_HOST: database
  image: docker.io/presslabs/php-runtime:8.0
  name: test
  user: root
- commands:
  - /usr/local/bin/setup-credentials-helper.sh
  group: publish
  image: quay.io/presslabs/build:latest
  name: publish
  when:
    event:
      include:
      - tag
