---
clone:
  disable: true
kind: pipeline
name: php-8.0
services:
- environment:
    MYSQL_DATABASE: wordpress_test
    MYSQL_PASSWORD: wordpress
    MYSQL_ROOT_PASSWORD: test
    MYSQL_USER: wordpress
  image: percona:5.7
  name: database
  pull: always
steps:
- image: plugins/git
  name: git
  pull: default
  settings:
    depth: 0
    tags: true
- commands:
  - pwd
  - apt update
  - apt install -y subversion
  - bash bin/install-wp-tests.sh wordpress_test wordpress wordpress database latest
  environment:
    WP_CORE_DIR: /drone/src/wordpress
    WP_TEST_DIR: /drone/src/wordpress-test-lib
  image: debian:latest
  name: prepare wordpress
- commands:
  - composer global require "phpunit/phpunit=4.8.*|5.7.*"
  - composer install -no --prefer-dist --no-dev -d ./src/
  environment:
    WP_CORE_DIR: /workspace/presslabs/toplytics/wordpress
    WP_TEST_DIR: /workspace/presslabs/toplytics/wordpress-test-lib
  image: docker.io/presslabs/php-runtime:8.0
  name: prepare php
- commands:
  - phpunit
  image: docker.io/presslabs/php-runtime:8.0
  name: test
- commands:
  - /usr/local/bin/setup-credentials-helper.sh
  group: publish
  image: quay.io/presslabs/build:latest
  name: publish
  when:
    event:
      include:
      - tag
