sudo: false
dist: xenial

services:
  - mysql

language: php

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - $HOME/.composer/cache

stages:
  - name: "Test"
  - name: "Deploy"

matrix:
  include:
    - php: 7.3
      stage: "Test"
      env: WP_VERSION=latest
    - php: 7.2
      stage: "Test"
      env: WP_VERSION=latest
    - php: 7.1
      stage: "Test"
      env: WP_VERSION=latest
    - php: 7.1
      stage: "Test"
      env: WP_VERSION=trunk
    - php: 7.0
      stage: "Test"
      env: WP_VERSION=latest
    - php: 7.3
      stage: "Deploy"
      deploy:
        provider: script
        skip_cleanup: true
        script: bash bin/deploy.sh
        on:
          tags: true
          repo: presslabs/toplytics
  allow_failures:
    - php: 7.3
      stage: "Test"
      env: WP_VERSION=latest
    - php: 7.1
      stage: "Test"
      env: WP_VERSION=trunk

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      composer global require "phpunit/phpunit=4.8.*|5.7.*"
    fi
  - composer install -no --prefer-dist --no-dev -d "./src/"

script:
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      phpunit
      WP_MULTISITE=1 phpunit
    fi

# Enable Travis auto-deployment
