site_name: toplytics
site_url: https://presslabs.org/toplytics/
repo_url: https://github.com/PressLabs/toplytics.git
repo_name: toplytics
site_author: Presslabs
theme_dir: docs-theme
docs_dir: documentation
site_dir: compiled_docs
extra:
  home_url: https://www.presslabs.com
markdown_extensions:
    - admonition
    - toc:
        baselevel: 1
pages:
    - General: 'index.md'
    - Usage: 'usage.md'
